---
- name: copy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes
  tags: mycnf

- name: create database
  shell: test -d /var/lib/mysql/mysql || mysqld --initialize-insecure --user=mysql

- name: start MySQL Instance
  service: name=mysqld state=started

- name: Enable MySQL Instance
  service: name=mysqld enabled=True

- name: Set new root Password from mysql_password_root
  mysql_user: name=root
              host="localhost"
              password="{{ mysql_password_root }}"
              check_implicit_admin=yes
              login_user="root"
              state=present
  tags: setrootpwd
  ignore_errors: yes

- name: create Users in MySQL
  no_log: true
  mysql_user: name="{{ item.name }}"
              host="{{ item.host }}"
              password="{{ item.password }}"
              priv='{{ item.priv }}'
              login_user="root"
              login_password="{{ mysql_password_root }}"
              state=present
  with_items: "{{ mysqlusers }}"
  when: item.create == True
  tags: dbusers
  ignore_errors: yes

- name: Create /home/mysql/etc directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: mysql
  with_items:
    - /home/mysql/etc
    - /home/mysql/log
    - /home/mysql/etc/mylvmbackuphook  

- name: Copy custom cnf-Files
  template:
    src:    "{{ item }}.j2"
    dest:   /home/mysql/etc/{{ item }}
    mode:   0600
    group:  mysql
    owner:  mysql
    backup: True
  with_items:
     - "{{ mysqlcustomcnf }}"
  tags: 
    - cron

- name: Create Backup Directories for MySQL
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: mysql
    group: mysql
  with_items:
    - "{{ mybinlogbackupdir }}"
    - "{{ mysqldumpdir }}"
    - "{{ mylvmbackupdir }}"
  tags: 
    - cron

- name: copy Hooks for mylvmbackup
  template:
    src:    "{{ item }}.j2"
    dest:   /home/mysql/etc/mylvmbackuphook/{{ item }}
    mode:   0700
    group:  mysql
    owner:  mysql
    backup: True
  with_items:
     - "backupsuccess"


- name: Create crontab entries for MySQL
  cron:
    name: "{{ item.name }}"
    cron_file: "/etc/cron.d/ansible_mysql"
    user: "mysql"
    disabled: "{{ item.disabled }}"
    day: "{{ item.day }}"
    weekday: "{{ item.weekday }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    job: "{{ item.jobname }}"
  with_items:
     - "{{ mysqlcron }}"
  tags: cron
