---
- name: copy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf backup=yes
  tags: mycnf

- name: create database
  shell: test -d /var/lib/mysql/mysql || mysqld --initialize-insecure --user=mysql

- name: start MySQL Instance
  service: name=mysqld state=started

- name: Enable MySQL Instance
  service: name=mysqld enabled=True

- name: Set new root Password from mysql_password_root
  mysql_user: name=root
              host="localhost"
              password="{{ mysql_password_root }}"
              check_implicit_admin=yes
              login_user="root"
              state=present
  tags: setrootpwd
  ignore_errors: yes

- name: create Users in MySQL
  no_log: true
  mysql_user: name="{{ item.name }}"
              host="{{ item.host }}"
              password="{{ item.password }}"
              priv='{{ item.priv }}'
              login_user="root"
              login_password="{{ mysql_password_root }}"
              state=present
  with_items: "{{ mysqlusers }}"
  when: item.create == True
  tags: dbusers
  ignore_errors: yes
