---

  - name: Remove existing .mylogin.cnf from User mysql
    become: yes
    become_user: mysql
    file: state=absent path=/home/mysql/.mylogin.cnf

  - name: create configuration .mylogin.cnf for User mysql
    no_log: True
    become: yes
    become_user: mysql
    expect:
       command: mysql_config_editor set  --login-path="{{ item.name }}" --user="{{ item.name }}" -p
       timeout: 2
       responses:
         'Enter password': '"{{ item.password }}"'
    with_items: "{{ mysqlusers }}"

