---

- name: Install yum Repository RPM on CentOS
  shell: yum install -y https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm ; exit 0
  args:
    executable: /bin/bash
  when: ansible_distribution == "CentOS"
  tags: yumrepo

- name: disable MySQL 8 on CentOS
  shell: yum-config-manager --disable {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "mysql80-community"
  when: ansible_distribution == "CentOS"
  tags: yumrepo

- name: enable Repos
  shell: yum-config-manager --enable {{ item }}
  args:
    executable: /bin/bash
  with_items:
     - "{{yumrepos}}"
  tags: yumrepo

- name: Install MySQL + Tools
  yum: name={{ item }} state=present
  with_items: "{{ mysql_rpm }}"

- name: add sudoers for systemctl start/stop mysqld and mylvmbackup
  template: src=sudoers_mysql dest=/etc/sudoers.d/mysql group=root owner=root mode=0644
  tags: sudo

- name: create home for mysql
  file: 
     path:  /home/mysql 
     owner: mysql
     group: mysql
     mode:  0750
     state: directory
  tags: osuser
  
- name: new home for mysql user
  user: 
     name:  mysql
     shell: /bin/bash 
     home:  /home/mysql
     state: present
     generate_ssh_key: True
  tags: osuser

- name: copy mybinlogcopy.sh
  copy: src=mybinlogcopy.sh dest=/usr/local/bin mode=755 owner=root group=root backup=no
  tags: mybinlogcopy
